-  name: My first Play
   hosts: web
   vars:
     http_port:8080
   tasks:
     - name: Install Apache Web Server
       yum:
         name: httpd
         state: present
     - name: Start Apache Web Server
       service:
         name: httpd
         state: started
     - name: Enable Port 8080
       firewalld:
         port: '{{ http_port }}'/tcp
         permanent: true
         state: enabled


